POST /token HTTP/1.1
Host: oauth2.googleapis.com
Content-length: 290
content-type: application/x-www-form-urlencoded
user-agent: google-oauth-playground

client_secret=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&grant_type=refresh_token&refresh_token=1%2F%2F04wZuE-reNSMCCgYIARAAGAQSNwF-L9IrTYuDDQavdpKAqBxRG5p9wz07OnTHuh_BE-kCcI61ZsE-hUg_0v4QZxiNDdMxlLZlKRM&client_id=40860710493408607104938-vjb5lvb3hr0k1r8vrgha580q7sshlhd8.apps.googleusercontent.com